//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autobot) DeepCopyInto(out *Autobot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autobot.
func (in *Autobot) DeepCopy() *Autobot {
	if in == nil {
		return nil
	}
	out := new(Autobot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Autobot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobotList) DeepCopyInto(out *AutobotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Autobot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobotList.
func (in *AutobotList) DeepCopy() *AutobotList {
	if in == nil {
		return nil
	}
	out := new(AutobotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutobotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobotSpec) DeepCopyInto(out *AutobotSpec) {
	*out = *in
	out.GenericSpec = in.GenericSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobotSpec.
func (in *AutobotSpec) DeepCopy() *AutobotSpec {
	if in == nil {
		return nil
	}
	out := new(AutobotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobotStatus) DeepCopyInto(out *AutobotStatus) {
	*out = *in
	out.GenericStatus = in.GenericStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobotStatus.
func (in *AutobotStatus) DeepCopy() *AutobotStatus {
	if in == nil {
		return nil
	}
	out := new(AutobotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decepticon) DeepCopyInto(out *Decepticon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decepticon.
func (in *Decepticon) DeepCopy() *Decepticon {
	if in == nil {
		return nil
	}
	out := new(Decepticon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Decepticon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecepticonList) DeepCopyInto(out *DecepticonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Decepticon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecepticonList.
func (in *DecepticonList) DeepCopy() *DecepticonList {
	if in == nil {
		return nil
	}
	out := new(DecepticonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecepticonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecepticonSpec) DeepCopyInto(out *DecepticonSpec) {
	*out = *in
	out.GenericSpec = in.GenericSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecepticonSpec.
func (in *DecepticonSpec) DeepCopy() *DecepticonSpec {
	if in == nil {
		return nil
	}
	out := new(DecepticonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecepticonStatus) DeepCopyInto(out *DecepticonStatus) {
	*out = *in
	out.GenericStatus = in.GenericStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecepticonStatus.
func (in *DecepticonStatus) DeepCopy() *DecepticonStatus {
	if in == nil {
		return nil
	}
	out := new(DecepticonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericSpec) DeepCopyInto(out *GenericSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericSpec.
func (in *GenericSpec) DeepCopy() *GenericSpec {
	if in == nil {
		return nil
	}
	out := new(GenericSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericStatus) DeepCopyInto(out *GenericStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericStatus.
func (in *GenericStatus) DeepCopy() *GenericStatus {
	if in == nil {
		return nil
	}
	out := new(GenericStatus)
	in.DeepCopyInto(out)
	return out
}
